server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1741534553A
    url: jdbc:mysql://localhost:3306/user_server
#  nacos地址
  cloud:
    nacos:
      server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8090
  application:
    name: user-server

    # redis配置
  redis:
    port: 6379
    host: localhost
    database: 0

  session:
    timeout: 2000
    store-type: redis



mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      #默认使用的是 assign_id,设置为auto,主键id自增
      id-type: auto
logging:
  level:
    com.lhj.mapper: DEBUG